name: main
on: [workflow_dispatch]
jobs:
  buildmobile:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: android ndk
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: android java
        uses: actions/setup-java@main
        with:
          distribution: temurin
          java-version: 11
      - name: install haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      - name: install library
        run: |
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib install lime
          haxelib run lime rebuild hxcpp
          haxelib install openfl
          haxelib install flixel
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib git faxe https://github.com/ashea-code/faxe
      - name: Setup Lime
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: compile
        run: haxelib run lime build android
      - name: upload artifact
        uses: actions/upload-artifact@main
        with:
          name: buildwindows
          path: export/release/android/bin/app/build/outputs/apk/debug
